### ISSUE TITLE
Uploading of results fails for a test that is excluded from the run

### ISSUE THREAD

**Issue by hok** [bbc/res#59]
A test that is excluded from a test run does not have a status in the res output:

```
 {
              "type": "Rspec::Test",
              "name": "test description",
              "urn": "./spec/file_spec.rb:291"
}
```

Trying to upload this res file results in the following error:

```
test_rail-api-0.4.0/lib/test_rail/api.rb:204:in `add_result_for_case': undefined method `to_sym' for nil:NilClass (NoMethodError)
```

in `lib/res/reporters/test_rail.rb:112:in `block in add_case_status'`

This could be fixed in several places:
- in the output generation by adding a status like `not_run/no_result`
- in the res gem, `add_result_for_case.rb:112` by excluding the not run test or updating the status to something descriptive
- in the test_rail-api gem where the error occurs (api.rb:204) before trying to convert nil to_sym

I'm not sure what is the preferred way of fixing it.

**Comment by Asimk21** [comment]
@hok 
How did it manage to exclude the results ? 
If rspec tests are excluded with 'xit' then status is set to "skipped".

**Comment by hok** [comment]
@Asimk21 it was excluded with a tag (--tag ~@<tag>) but I can use xit too.

**Comment by Asimk21** [comment]
There is no "Not Run" status in Test rail. How about setting default status to "blocked" ? Check branch 'rspec_not_run' and try if that helps.
