### ISSUE TITLE
Cucumber2 Formatter appears to report failling outlines as passed...

### ISSUE THREAD

**Issue by mcrmfc** [bbc/res#69]
Hi,

It appears that the Cucumber2 formatter when encountering a scenario outline will report the overall scenario as passed if it contains failing examples (unless it's the last example - in which case its ok).

As hive overall results appear to hinge off this it seems to mean you can get a passing CI job despite your tests actually failing.

I have produced a reduced test case example for you:

https://github.com/mcrmfc/cuke-res-issue

You can see what happens here:

https://github.com/mcrmfc/cuke-res-issue/blob/master/out.res
 
I will shortly push a PR with a sort of 'fix'....

However I think this probably requires a bit more thought and some more tests around it, as with the current coverage I am certain that the 'fix' I have made would break other use cases.

I don't mind doing that just wanted to run by you first in case I have missed something?

Cheers
Matt.

**Comment by wordswords** [comment]
Thanks for spotting this! Looks like something we need to address. I don't think you have missed anything from the initial description. If you have the time we would definitely welcome a PR with tests around it, then we will consider it for merge and you will have contributed to the open source development of Res.

**Comment by mcrmfc** [comment]
Hi, apologies but after reviewing my current workload I don't think I am going to get a chance to look at this any time soon.  We will have to run on a fork of res for the moment to ensure that Hive reports failed builds accurately.
